name: Bug Report
description: Report a bug
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a crash here, please make sure you are on the latest mod version for your version of Minecraft.

  - type: input
    attributes:
      label: Version
      description: Please provide the version of the mod you're running. This can be found in the file name of the mod jar.
      placeholder: ex. 2.0.0-mc1.20.1
    validations:
      required: true

  - type: textarea
    attributes:
      label: Observed behavior
      description: What happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: |
        Logs are generally quite useful if there's been a crash or error. (`logs/latest.log` can be uploaded to https://mclo.gs or dropped here)
        Screenshots/videos, or instructions to help reproduce the issue are appreciated if the cause is not obvious.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Other
      description: |
        Any other information you think may be helpful or relevant
    validations:
      required: false
