blank_issues_enabled: true
contact_links:
  - name: Wiki
    url: https://github.com/John-Paul-R/server-announce/wiki
    about: Information describing how to use Server Announce
  - name: Join Discord
    url: https://discord.jpcode.dev/
    about: A place for questions & discussion about the Server Announce
